spring:
  data:
    redis:
      writer:
        port: 6379
        host: redis-writer
      reader:
        port: 6380
        host: redis-reader

netty:
  tcp-port: 8090
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100
