version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  tcp:
    image: vehicle-gateway-tcp
    ports:
      - "8090:8090"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis

  rest:
    image: vehicle-gateway-rest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
