version: '3.9'

services:
  tcp:
    image: vehicle-gateway-tcp:latest
    ports:
      - "8090:8090"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    deploy:
      replicas: 2

  rest:
    image: vehicle-gateway-rest:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    deploy:
      replicas: 2